### ISSUE TITLE
src __getitem__ bug

### ISSUE THREAD

**Issue by nickjsr** [ccharp/dplyPY#23] opened 2022-02-24 05:46 UTC
Found a potential bug of __getitem__ when I implemented check_null on indexing a column of a dataframe. Details in https://github.com/ccharp/dplyPY/issues/9. In short, our __getitem__ treats dataframe[column name] as dataframe[index of column name].

**Comment by nickjsr** [comment] 2022-02-24 05:51
I think of a way to bypass this bug: in src dplypy.py __init__, we have self.pandas_df, at the same place storing column names may be a good idea.  I am not sure if it is a good practice.

**Comment by ccharp** [comment] 2022-02-24 06:04
Looking into this...

**Comment by nickjsr** [comment] 2022-02-24 06:06
Update: adding pandas_df.columns is not needed. There was a bug in my pipeline. Now we have fixed it

**Comment by ccharp** [comment] 2022-02-24 06:09
@nickjsr if I'm understanding correctly, this bug does not exist? I need to write tests for __get_item__() anyway, but you can close this of the issue is resolved. I'm signing off for the night

**Comment by nickjsr** [comment] 2022-02-24 06:29
We can test getitem later

**Closed** 2022-02-24 06:28 UTC
Labels: bug, help wanted
